name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java (for Android tooling)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Add Android SDK tools to PATH
        shell: bash
        run: |
          echo "${ANDROID_HOME}/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "${ANDROID_HOME}/platform-tools" >> $GITHUB_PATH
          echo "${ANDROID_HOME}/emulator" >> $GITHUB_PATH

      - name: Ensure Android SDK platforms are installed
        shell: bash
        run: |
          sdkmanager --sdk_root="${ANDROID_HOME}" "platforms;android-33"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore AppodealXamarin.sln

      - name: Build solution
        run: msbuild AppodealXamarin.sln /p:Configuration=Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppodealXamarinPlugin
          path: |
            **/bin/Release/*.dll
            **/bin/Release/*.nupkg
